<a href="https://colab.research.google.com/github/Marcux777/Ci-ncia-de-Dados/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NumPy

O NumPy, abreviação de **Numerical Python**, é uma biblioteca fundamental para a ciência de dados em Python. Ela oferece um array multidimensional de alto desempenho e ferramentas abrangentes para manipular e analisar dados numéricos com eficiência.

Para entendermos melhor o papel crucial do NumPy na ciência de dados, vamos explorar suas principais funcionalidades e como elas se aplicam a tarefas comuns de análise de dados:

**1. Criação e Manipulação de Arrays:**

* **Arrays NumPy:** A estrutura de dados central do NumPy é o array, que armazena elementos do mesmo tipo em uma estrutura multidimensional. Arrays NumPy são homogêneos, ou seja, todos os elementos possuem o mesmo tipo de dados (int, float, bool, etc.), o que os torna muito mais eficientes para cálculos do que listas em Python puro.
* **Criação de Arrays:** O NumPy oferece diversas funções para criar arrays, como `np.array()`, `np.zeros()`, `np.ones()`, `np.full()`, entre outras. Cada função permite especificar o tipo de dados, as dimensões e os valores iniciais do array.

Exemplos:

In [2]:
import numpy as np

In [6]:
# Criando um array de 10 zeros de tipo float
array_zeros = np.zeros(10, dtype=float)
print(array_zeros)

# Criando um array de 5 ones de tipo inteiro
array_ones = np.ones(5, dtype=int)
print('\n\n',array_ones)

# Criando um array 3x3 preenchido com o valor 7
array_full = np.full((3, 3), 7)
print('\n\n',array_full)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


 [1 1 1 1 1]


 [[7 7 7]
 [7 7 7]
 [7 7 7]]


**2. Indexação e Fatiamento:**

* **Acesso a Elementos Específicos:** O NumPy fornece mecanismos eficientes para acessar elementos individuais ou subconjuntos de um array usando índices e fatiamento.
* **Indexação:** Os índices entre colchetes `[]` permitem selecionar elementos específicos de um array, especificando suas posições nas dimensões.
* **Fatiamento:** O fatiamento com colchetes `[]` e dois pontos `:` permite selecionar subconjuntos de um array, definindo um intervalo de índices para cada dimensão.

Exemplos:

In [7]:
# Acessando o quinto elemento do array
array_numeros = np.array([1, 2, 3, 4, 5])
quinto_elemento = array_numeros[4]  # Resultado: 5
print(quinto_elemento)

# Selecionando os elementos da segunda à quarta linha
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
linhas_2_a_4 = matriz[1:4, :]  # Resultado: [[4 5 6], [7 8 9]]
print("\n\n", linhas_2_a_4)

# Selecionando a segunda coluna de todas as linhas
coluna_2 = matriz[:, 1]  # Resultado: [2 5 8]
print("\n\n", coluna_2)

5


 [[4 5 6]
 [7 8 9]]


 [2 5 8]


**3. Operações Matemáticas e Estatísticas:**

* **Operações Vetorizadas:** O NumPy permite realizar operações matemáticas e estatísticas em arrays inteiros, sem a necessidade de loops lentos. As operações são aplicadas elemento a elemento em todo o array.
* **Funções Matemáticas:** O NumPy oferece uma ampla gama de funções matemáticas embutidas, como `np.sin()`, `np.cos()`, `np.exp()`, `np.log()`, `np.sqrt()`, entre muitas outras.
* **Funções Estatísticas:** O NumPy também fornece funções estatísticas para calcular medidas como média, mediana, desvio padrão, variância, quartis, etc.

Exemplos:

In [8]:
# Calculando o seno de todos os elementos do array
angulos = np.array([30, 60, 90])
radians = np.radians(angulos)
senos = np.sin(radians)
print(senos)

    # Calculando a média dos elementos do array
numeros = np.array([10, 20, 30, 40, 50])
media = np.mean(numeros)  # Resultado: 30.0
print("\n\n",media)

    # Calculando a variância dos elementos do array
variancia = np.var(numeros)  # Resultado: 200.0
print("\n\n", variancia)

[0.5       0.8660254 1.       ]


 30.0


 200.0


**4. Transformações de Arrays:**

* **Reorganização de Arrays:** O NumPy oferece diversas funções para reorganizar e modificar a estrutura de arrays.
* **Mudança de Forma:** A função `np.reshape()` permite alterar a forma de um array sem modificar seus dados.
* **Transposição:** A função `np.transpose()` troca as linhas e colunas de um array.
* **Agrupamento e Ordenação:** Funções como `np.sort()`, `np.argsort()`, `np.unique()`, e `np.count_elements()` permitem agrupar, ordenar e contar elementos em arrays.

Exemplos:

In [12]:
# Alterando a forma de um array para (2, 3)
array_original = np.array([1, 2, 3, 4, 5, 6])
array_remodelado = np.reshape(array_original, (2, 3))  # Resultado: [[1 2 3], [4 5 6]]
print(array_remodelado)

    # Transpondo um array
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matriz_transposta = np.transpose(matriz)  # Resultado: [[1 4 7], [2 5 8], [3 6 9]]
print('\n\n',matriz_transposta,'\n\n')

    # Ordenando um array e obtendo os índices de ordenação
numeros_desordenados = np.array([5, 2, 4, 1, 3])
numeros_ordenados, indices_ordenacao = np.sort(numeros_desordenados), np.argsort(numeros_desordenados)
print(numeros_ordenados)
print(indices_ordenacao)
    # Resultado: numeros_ordenados = [1 2 3 4 5], indices_ordenacao = [3 1 2 0 4]

[[1 2 3]
 [4 5 6]]


 [[1 4 7]
 [2 5 8]
 [3 6 9]] 


[1 2 3 4 5]
[3 1 4 2 0]


**5. Operações com Outros Objetos Python:**

* **Integração com Python Puro:** O NumPy se integra perfeitamente com o Python puro, permitindo que você utilize arrays NumPy em conjunto com outras estruturas de dados e funções do Python.
* **Conversão de Tipos:** Funções como `np.asarray()`, `np.frompyfunc()`, e `np.vectorize()` permitem converter objetos Python em arrays NumPy e vice-versa.
* **Operações com Pandas:** O NumPy é a base para a biblioteca Pandas, popular para análise de dados em Python. Arrays NumPy podem ser facilmente convertidos em DataFrames Pandas para análises mais complexas.

Exemplos:

In [13]:
# Convertendo uma lista em um array NumPy
lista_numeros = [10, 20, 30]
array_numeros = np.asarray(lista_numeros)  # Resultado: array([10, 20, 30])

    # Criando uma função Python que eleva ao quadrado e aplicando-a em um array NumPy
def elevar_ao_quadrado(x):
    return x ** 2

numeros_quadrados = np.vectorize(elevar_ao_quadrado)(array_numeros)  # Resultado: array([100 400 900])
print(numeros_quadrados)

[100 400 900]


**6. Otimização de Desempenho:**

* **Cálculos Vetorizados Eficientes:** O NumPy utiliza técnicas de computação vetorial otimizadas para realizar cálculos em arrays de forma muito mais rápida do que loops em Python puro.
* **Suporte a Multiprocessamento:** O NumPy oferece suporte para multiprocessamento, permitindo distribuir cálculos em vários núcleos do processador para acelerar ainda mais as análises.
* **Bibliotecas Externas:** Bibliotecas como Cython e Numba podem ser usadas para compilar código NumPy em C ou Python otimizado, obtendo ganhos de desempenho ainda maiores.

Exemplos:

In [ ]:
# Calculando a soma de um array de 1 milhão de elementos usando um loop Python puro
import time

tempo_inicio = time.time()
soma_loop = 0
for numero in range(1000000):
    soma_loop += numero

tempo_final = time.time()
print(f"Tempo de loop: {tempo_final - tempo_inicio}")


Tempo de loop: 0.1387636661529541


In [ ]:
# Calculando a soma do mesmo array usando o NumPy
tempo_inicio = time.time()
soma_numpy = np.sum(np.arange(1000000))
tempo_final = time.time()
print(f"Tempo NumPy: {tempo_final - tempo_inicio}")

Tempo NumPy: 0.007683753967285156


Tipicamente, a versão NumPy será significativamente mais rápida devido à maneira otimizada como processa os elementos do array.

**7. Manipulação de Arquivos de Dados:**

* **Leitura e Escrita de Arquivos:** NumPy possui funções para ler e salvar dados de arquivos em diversos formatos.
* **Arquivos .txt ou .csv:** Funções como `np.loadtxt()` e `np.savetxt()` para ler ou salvar arrays como arquivos de texto.
* **Formatos Binários:** Funções como `np.save()` e `np.load()` para gravar e carregar arrays em formatos binários que costumam ser mais compactos e eficientes para grandes conjuntos de dados.

Exemplos:

In [14]:
# Saving an array to a text file .csv
from numpy import savetxt
dados = np.array([[1, 2, 3], [4, 5, 6]])
savetxt('meus_dados.csv', dados, delimiter=',')

# Loading data from a text file .txt
from numpy import loadtxt
dados_carregados = loadtxt('meus_dados.csv', delimiter=',')
print(dados_carregados)

[[1. 2. 3.]
 [4. 5. 6.]]


**Aplicações Comuns do NumPy na Ciência de Dados**

* **Pré-processamento de dados:** Utilizar arrays NumPy para limpeza de dados, normalização e padronização antes de treinar modelos.
* **Engenharia de Recursos:** Transformar e manipular dados numéricos, extrair recursos ou construir representações para modelos de Machine Learning.
* **Álgebra Linear:** Implementar operações fundamentais de álgebra linear, essenciais para muitos algoritmos estatísticos e de aprendizado de máquina.
* **Implementação de Algoritmos de ML:** Utilizar as poderosas operações NumPy para construir algoritmos de aprendizado de máquina, como regressão linear e redes neurais.
* **Visualização de Dados:** Combinar NumPy com bibliotecas de visualização como Matplotlib e Seaborn para criar gráficos e diagramas informativos.
